import type { AuditLog, Expense, ExpenseAlert, UserProfile } from './types'

// Seed data shared by every page until PostgreSQL is connected.
// Each getter mirrors a future SQL query (see db/schema.sql), so pages
// only need their data source swapped — not their structure.

const USER_ID = 'usr_01'

const profile: UserProfile = {
  id: USER_ID,
  name: 'Aarav Mehta',
  email: 'aarav@mehtastudio.co',
  businessName: 'Mehta Design Studio',
  occupation: 'Freelance Product Designer',
  currency: 'USD',
  monthlyBudget: 2500,
  categoryBudgets: {
    food: 400,
    travel: 700,
    office: 250,
    software: 450,
    utilities: 200,
    marketing: 400,
  },
  joinedAt: '2026-03-14T09:00:00.000Z',
}

const expenses: Expense[] = [
  {
    id: 'exp_1012',
    userId: USER_ID,
    merchant: 'Blue Bottle Coffee',
    amount: 18.75,
    taxAmount: 1.5,
    currency: 'USD',
    date: '2026-10-06T00:00:00.000Z',
    category: 'food',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.97,
    notes: 'Client meeting with Northwind team',
    receiptUrl: '/images/receipt-hero.png',
    items: [
      { description: 'Cappuccino', quantity: 2, amount: 10.5 },
      { description: 'Almond croissant', quantity: 1, amount: 6.75 },
    ],
    createdAt: '2026-10-06T10:12:00.000Z',
  },
  {
    id: 'exp_1011',
    userId: USER_ID,
    merchant: 'Figma Inc.',
    amount: 45,
    taxAmount: 0,
    currency: 'USD',
    date: '2026-10-04T00:00:00.000Z',
    category: 'software',
    paymentMethod: 'card',
    status: 'verified',
    source: 'tesseract',
    confidence: 0.91,
    items: [{ description: 'Professional plan — 3 seats', quantity: 1, amount: 45 }],
    createdAt: '2026-10-04T08:30:00.000Z',
  },
  {
    id: 'exp_1010',
    userId: USER_ID,
    merchant: 'Uber',
    amount: 32.4,
    taxAmount: 2.1,
    currency: 'USD',
    date: '2026-10-03T00:00:00.000Z',
    category: 'travel',
    paymentMethod: 'card',
    status: 'pending',
    source: 'tesseract',
    confidence: 0.68,
    notes: 'Ride to client office',
    items: [{ description: 'Trip — Downtown to Harbor St', quantity: 1, amount: 30.3 }],
    createdAt: '2026-10-03T18:45:00.000Z',
  },
  {
    id: 'exp_1009',
    userId: USER_ID,
    merchant: 'Staples',
    amount: 86.2,
    taxAmount: 6.9,
    currency: 'USD',
    date: '2026-10-02T00:00:00.000Z',
    category: 'office',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.95,
    items: [
      { description: 'A4 paper (5 reams)', quantity: 1, amount: 39.99 },
      { description: 'Ink cartridge', quantity: 1, amount: 39.31 },
    ],
    createdAt: '2026-10-02T14:10:00.000Z',
  },
  {
    id: 'exp_1008',
    userId: USER_ID,
    merchant: 'Uber',
    amount: 32.4,
    taxAmount: 2.1,
    currency: 'USD',
    date: '2026-10-03T00:00:00.000Z',
    category: 'travel',
    paymentMethod: 'card',
    status: 'flagged',
    source: 'tesseract',
    confidence: 0.72,
    notes: 'Possible duplicate of exp_1010',
    items: [{ description: 'Trip — Downtown to Harbor St', quantity: 1, amount: 30.3 }],
    createdAt: '2026-10-03T19:02:00.000Z',
  },
  {
    id: 'exp_1007',
    userId: USER_ID,
    merchant: 'Comcast Business',
    amount: 129.99,
    taxAmount: 9.1,
    currency: 'USD',
    date: '2026-09-28T00:00:00.000Z',
    category: 'utilities',
    paymentMethod: 'bank_transfer',
    status: 'verified',
    source: 'gemini',
    confidence: 0.98,
    items: [{ description: 'Business internet — Sept', quantity: 1, amount: 120.89 }],
    createdAt: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'exp_1006',
    userId: USER_ID,
    merchant: 'Delta Air Lines',
    amount: 412.6,
    taxAmount: 38.4,
    currency: 'USD',
    date: '2026-09-19T00:00:00.000Z',
    category: 'travel',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.96,
    notes: 'Design conference — Austin',
    items: [{ description: 'Economy round trip SFO–AUS', quantity: 1, amount: 374.2 }],
    createdAt: '2026-09-19T07:20:00.000Z',
  },
  {
    id: 'exp_1005',
    userId: USER_ID,
    merchant: 'Meta Ads',
    amount: 250,
    taxAmount: 0,
    currency: 'USD',
    date: '2026-09-15T00:00:00.000Z',
    category: 'marketing',
    paymentMethod: 'card',
    status: 'verified',
    source: 'manual',
    confidence: 1,
    items: [{ description: 'Portfolio campaign', quantity: 1, amount: 250 }],
    createdAt: '2026-09-15T12:00:00.000Z',
  },
  {
    id: 'exp_1004',
    userId: USER_ID,
    merchant: 'Sweetgreen',
    amount: 24.35,
    taxAmount: 2.0,
    currency: 'USD',
    date: '2026-09-11T00:00:00.000Z',
    category: 'food',
    paymentMethod: 'upi',
    status: 'verified',
    source: 'tesseract',
    confidence: 0.88,
    items: [{ description: 'Harvest bowl', quantity: 2, amount: 22.35 }],
    createdAt: '2026-09-11T13:15:00.000Z',
  },
  {
    id: 'exp_1003',
    userId: USER_ID,
    merchant: 'Adobe',
    amount: 59.99,
    taxAmount: 0,
    currency: 'USD',
    date: '2026-09-05T00:00:00.000Z',
    category: 'software',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.99,
    items: [{ description: 'Creative Cloud — monthly', quantity: 1, amount: 59.99 }],
    createdAt: '2026-09-05T06:00:00.000Z',
  },
  {
    id: 'exp_1002',
    userId: USER_ID,
    merchant: 'Hilton Garden Inn',
    amount: 389,
    taxAmount: 42.5,
    currency: 'USD',
    date: '2026-08-22T00:00:00.000Z',
    category: 'travel',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.94,
    items: [{ description: '2 nights — King room', quantity: 2, amount: 173.25 }],
    createdAt: '2026-08-22T20:00:00.000Z',
  },
  {
    id: 'exp_1001',
    userId: USER_ID,
    merchant: 'Office Depot',
    amount: 142.5,
    taxAmount: 11.4,
    currency: 'USD',
    date: '2026-07-30T00:00:00.000Z',
    category: 'office',
    paymentMethod: 'cash',
    status: 'verified',
    source: 'tesseract',
    confidence: 0.86,
    items: [{ description: 'Ergonomic desk mat', quantity: 1, amount: 131.1 }],
    createdAt: '2026-07-30T16:40:00.000Z',
  },
  {
    id: 'exp_1000',
    userId: USER_ID,
    merchant: 'Notion Labs',
    amount: 96,
    taxAmount: 0,
    currency: 'USD',
    date: '2026-06-12T00:00:00.000Z',
    category: 'software',
    paymentMethod: 'card',
    status: 'verified',
    source: 'gemini',
    confidence: 0.99,
    items: [{ description: 'Plus plan — annual', quantity: 1, amount: 96 }],
    createdAt: '2026-06-12T09:30:00.000Z',
  },
]

const alerts: ExpenseAlert[] = [
  {
    id: 'alt_05',
    userId: USER_ID,
    type: 'duplicate',
    severity: 'critical',
    title: 'Possible duplicate receipt',
    message: 'Two Uber receipts for $32.40 on Oct 3 were scanned within 20 minutes of each other.',
    expenseId: 'exp_1008',
    read: false,
    createdAt: '2026-10-03T19:05:00.000Z',
  },
  {
    id: 'alt_04',
    userId: USER_ID,
    type: 'low_confidence',
    severity: 'warning',
    title: 'Low extraction confidence',
    message: 'OCR confidence for the Uber receipt was 68%. Review the extracted fields before verifying.',
    expenseId: 'exp_1010',
    read: false,
    createdAt: '2026-10-03T18:46:00.000Z',
  },
  {
    id: 'alt_03',
    userId: USER_ID,
    type: 'budget',
    severity: 'warning',
    title: 'Software budget at 80%',
    message: 'You have used most of your monthly software budget with 24 days remaining.',
    read: false,
    createdAt: '2026-10-04T08:31:00.000Z',
  },
  {
    id: 'alt_02',
    userId: USER_ID,
    type: 'anomaly',
    severity: 'info',
    title: 'Travel spend above average',
    message: 'September travel spend was 2.1× your 3-month average, driven by the Austin conference.',
    expenseId: 'exp_1006',
    read: true,
    createdAt: '2026-09-30T09:00:00.000Z',
  },
  {
    id: 'alt_01',
    userId: USER_ID,
    type: 'reminder',
    severity: 'info',
    title: 'Monthly report ready',
    message: 'Your September expense summary is ready to export for your accountant.',
    read: true,
    createdAt: '2026-10-01T08:00:00.000Z',
  },
]

const auditLogs: AuditLog[] = [
  { id: 'log_09', userId: USER_ID, action: 'expense.created', entityType: 'expense', entityId: 'exp_1012', detail: 'Created from Gemini Vision extraction', createdAt: '2026-10-06T10:12:00.000Z' },
  { id: 'log_08', userId: USER_ID, action: 'receipt.scanned', entityType: 'receipt', entityId: 'exp_1012', detail: 'Receipt captured via camera', createdAt: '2026-10-06T10:11:00.000Z' },
  { id: 'log_07', userId: USER_ID, action: 'expense.updated', entityType: 'expense', entityId: 'exp_1011', detail: 'Category changed: Other → Software', createdAt: '2026-10-04T08:35:00.000Z' },
  { id: 'log_06', userId: USER_ID, action: 'expense.created', entityType: 'expense', entityId: 'exp_1008', detail: 'Created from Tesseract OCR extraction', createdAt: '2026-10-03T19:02:00.000Z' },
  { id: 'log_05', userId: USER_ID, action: 'expense.created', entityType: 'expense', entityId: 'exp_1010', detail: 'Created from Tesseract OCR extraction', createdAt: '2026-10-03T18:45:00.000Z' },
  { id: 'log_04', userId: USER_ID, action: 'user.login', entityType: 'user', entityId: USER_ID, detail: 'Signed in from Chrome on macOS', createdAt: '2026-10-03T18:40:00.000Z' },
  { id: 'log_03', userId: USER_ID, action: 'expense.updated', entityType: 'expense', entityId: 'exp_1009', detail: 'Total corrected: $86.02 → $86.20', createdAt: '2026-10-02T14:15:00.000Z' },
  { id: 'log_02', userId: USER_ID, action: 'profile.updated', entityType: 'profile', entityId: USER_ID, detail: 'Monthly budget set to $2,500', createdAt: '2026-09-30T11:00:00.000Z' },
]

export async function getCurrentUser(): Promise<UserProfile> {
  return profile
}

export async function getExpenses(): Promise<Expense[]> {
  return [...expenses].sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt))
}

export async function getExpenseById(id: string): Promise<Expense | undefined> {
  return expenses.find((e) => e.id === id)
}

export async function getAlerts(): Promise<ExpenseAlert[]> {
  return [...alerts].sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export async function getAuditLogs(entityId?: string): Promise<AuditLog[]> {
  const logs = entityId ? auditLogs.filter((l) => l.entityId === entityId) : auditLogs
  return [...logs].sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export const REFERENCE_DATE = new Date('2026-10-07T12:00:00.000Z')
